version: '2'

services:
    sonar:
        image: sonarqube:community
        ports:
            - "9000:9000" 
        depends_on:
            - sonardb
        environment:
            - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonarmysql
        volumes:
            - ./sonarqube/sonarqube_data:/opt/sonarqube/data
            - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
            - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
    sonardb:
        image: mysql:5.7.17
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - "33066:3306"
        environment:
            MYSQL_DATABASE: sonar
            MYSQL_USER: sonar
            MYSQL_PASSWORD: sonarmysql
            MYSQL_ROOT_PASSWORD: sonarroot
        command: [--max-allowed-packet=67108864]