version: '2'

services:
  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-4
    environment:
    - DB_USER=owncloud
    - DB_PASS=12345678
    - DB_NAME=owncloud_db
    volumes:
    - ./postgresql:/var/lib/postgresql

  owncloud:
    restart: always
    image: sameersbn/owncloud:10.0.10-0
    command: app:owncloud
    environment:
    - DEBUG=false
    - TZ=Asia/Bangkok
    - DB_TYPE=pgsql
    - DB_HOST=postgresql
    - DB_USER=owncloud
    - DB_PASS=12345678
    - DB_NAME=owncloud_db

    - OWNCLOUD_URL=http://owncloud.test:8880

    - OWNCLOUD_ADMIN_USER=devmix
    - OWNCLOUD_ADMIN_PASSWORD=12345678

    - OWNCLOUD_UPLOAD_MAX_FILESIZE=4G
    - OWNCLOUD_MAX_FILE_UPLOADS=20

    - OWNCLOUD_BACKUPS_EXPIRY=0
    depends_on:
    - postgresql
    volumes:
    - ./owncloud:/var/lib/owncloud

  nginx:
    restart: always
    image: sameersbn/owncloud:10.0.10-0
    command: app:nginx
    environment:
    - OWNCLOUD_PHP_FPM_HOST=owncloud
    - OWNCLOUD_PHP_FPM_PORT=9000
    depends_on:
    - owncloud
    ports:
    - "8880:80"