version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=abcprintf
      - RABBITMQ_DEFAULT_PASS=Password@123
    ports:
      - 5672:5672
      - 15672:15672 # UI
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/