version: '3.7'

services:
  # Elasticsearch
  es-app:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: es-app
    environment:
      # - node.name=es-app
      # - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es-app
      - discovery.type=single-node
      # - cluster.initial_master_nodes=es-app
      # - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-net
  # Kibana
  kb-app:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kb-app
    environment:
      - ELASTICSEARCH_HOSTS=http://es-app:9200
    ports:
      - 5601:5601
    networks:
      - es-net
    depends_on:
      - es-app

networks:
  es-net:
    driver: bridge