version: '3.7'

services:

  mongo-database:
    container_name: mongodb_version_50
    image: mongo:5.0
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789
      MONGO_INITDB_DATABASE: example
      MONGO_INITDB_USERNAME: abcprintf
      MONGO_INITDB_PASSWORD: 111111111
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db