version: '3.7'

# The services of your app
services:
  jenkins-app:
    image: jenkins/jenkins:latest
    container_name: jenkins-service
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins-home-data:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
    restart: always