version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: